#pragma once

#include "Node.hpp"
#include "ListNode.hpp"
#include "EchoNode.hpp"
#include "FunctionDefineNode.hpp"
#include "ReturnNode.hpp"
#include "VariableNode.hpp"
#include "BinaryOperationNode.hpp"
#include "DeclarationNode.hpp"
#include "AssignmentNode.hpp"
#include "ScalarNode.hpp"
#include "IfNode.hpp"
#include "ElseNode.hpp"
#include "WhileNode.hpp"
#include "ForNode.hpp"
#include "ParameterNode.hpp"
#include "FunctionCallNode.hpp"