#pragma once

#include <iostream>
class AssignmentNode;
class BinaryOperationNode;
class DeclarationNode;
class EchoNode;
class ElseNode;
class ForNode;
class FunctionNode;
class IfNode;
class ListNode;
class ReturnNode;
class ScalarNode;
class VariableNode;
class WhileNode;
class FunctionDefineNode;
class FunctionCallNode;
class ParameterNode;
class ClassMethodNode;
class ClassMemNode;
class ClassDefineNode;
class ClassCallNode;
class NewNode;
class BreakNode;
class ContinueNode;
class StaticCallNode;
