#pragma once
#ifndef TYPE_DEFINITIONS_H
#define TYPE_DEFINITIONS_H

enum TypesIds {
	ERROR_TYPE_ID = 0, INTEGER_TYPE_ID, VOID_TYPE_ID, FLOAT_TYPE_ID, CHARACTER_TYPE_ID, CLASS_TYPE_ID, BOOLEAN_TYPE_ID, STRING_TYPE_ID
};


#endif
