/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include<stdlib.h>
#include<unistd.h>
#include<iostream>
using namespace std;
/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 196
#define YY_END_OF_BUFFER 197
static yyconst short int yy_accept[538] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  197,    8,
        9,    8,   15,   16,   15,  196,   30,   28,   29,   30,
       47,   40,   41,   47,   47,  196,  196,   52,   51,   50,
       53,  196,  196,   56,  195,   13,   12,   74,   25,   10,
       77,   73,   65,   24,   82,   83,   71,   68,   58,   69,
       70,   72,   17,   61,   62,   66,   59,   67,   60,   76,
      191,   78,   57,   79,   64,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,   80,   63,   81,   75,

        0,    3,    2,   14,   27,   26,   46,   39,   38,   37,
       34,   36,   31,   32,   33,   35,   48,   49,   52,   51,
       54,   55,   56,  143,   10,    0,  192,  152,    6,   88,
       84,    0,  159,  153,  133,  158,  101,  151,  156,    0,
       18,   97,   11,   10,  105,   19,   17,  193,  193,  108,
      168,  145,  143,  140,  107,  141,  170,  191,    0,   86,
      182,  191,  191,  191,  191,   87,  191,  191,  191,  191,
      191,  191,  191,  191,  106,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  131,  191,
      191,  191,  191,  191,  191,  149,  191,  191,  191,  191,

      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      100,  157,   89,    7,    5,    4,    0,    0,   46,    0,
       48,   49,   54,  144,  194,  192,    0,  160,  110,    0,
        0,  193,    0,   20,  169,  142,  171,  191,  191,  191,
      191,  191,  148,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  121,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  126,  191,  191,
      191,  191,  191,  191,  184,  191,  191,  191,  155,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      176,  191,  179,  180,  191,  191,  150,  191,    0,    0,

        0,    0,    0,  194,    0,    0,   18,    0,   19,   20,
      191,  191,  191,  191,  191,  191,  188,  191,  191,   92,
      191,  187,  191,  191,  191,  191,  191,  191,  191,  109,
      111,  191,  191,  191,  191,  191,  191,  120,  191,  191,
      191,  191,  191,  191,  191,  130,  191,  191,  191,  191,
      191,  147,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,   21,  191,  190,  191,  191,    1,
       45,    0,   43,    0,   42,    0,  191,  191,  191,  191,
      191,   85,  191,   90,  191,   93,   94,   96,   98,  191,
      191,  191,  191,  191,  113,  191,  191,  117,  191,  191,

      191,   22,  124,  186,  191,  191,  191,  191,  191,  191,
      191,  191,  139,  191,  161,  191,  191,  191,  191,  191,
      191,  191,  191,  174,  175,  177,  181,  183,   45,    0,
       44,    0,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  185,  112,  191,  115,  191,  191,  191,  191,
      191,  191,  129,  191,  191,  191,  191,  191,  191,  191,
      191,  163,  191,  167,  172,  189,  173,  178,  191,  104,
      191,  191,  191,  188,  191,  191,  102,  103,  191,  191,
      191,  191,  122,  125,  127,  191,  191,  134,  191,  191,
      191,  191,  162,  191,  165,  191,  123,  146,   23,   91,

       99,  191,  191,  191,  119,  128,  191,  191,  191,  191,
      191,  191,  191,  191,   95,  191,  191,  118,  191,  191,
      191,  137,  138,  154,  164,  191,  114,  116,  132,  191,
      136,  191,  191,  191,  135,  166,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       29,   29,   34,   29,   29,   35,   29,   36,   29,   29,
       29,   37,   38,   29,   29,   29,   29,   29,   29,   29,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   29,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   29,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[72] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    4,    1,    1,
        3,    1,    1,    3,    3,    3,    5,    6,    3,    7,
        1,    1,    1,    1,    1,    1,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    9,    3,
       10,    1,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[567] =
    {   0,
        0,    1,    2,    3,    0,    0,    4,    7,    5,    6,
      804,  803,   47,    0,  118,    0,  189,    0,  810,  786,
      785,   10,  813,  813,  788,  813,  813,  813,  813,  250,
      813,  813,  813,    0,  256,    0,    0,  786,    0,  813,
      813,    0,  780,    0,  813,  813,  813,  780,  813,    0,
      257,    1,   10,  813,  740,  813,    7,   13,  813,    5,
      260,  267,  247,  781,  813,   15,   17,  245,  776,  813,
        0,  280,  813,  813,  776,  756,  238,  228,  249,  262,
      269,  282,  235,  252,  746,  283,  737,  269,  748,  275,
      251,  261,  284,  744,  737,  741,  784,  285,  813,  813,

      765,  766,  306,  813,  813,  813,  321,  813,  813,  813,
      813,  813,  813,  813,  813,  813,    0,    0,  769,    0,
        0,  813,    0,  764,    0,  351,    0,  813,  813,  813,
      813,  731,  762,  813,  813,  813,  813,  813,  813,  767,
      324,  813,  813,    0,  813,  326,  329,    0,  333,  813,
      760,  813,  813,  759,  813,  813,  758,    0,  340,  813,
      813,  345,  720,  733,  719,    0,  721,  729,  325,  732,
      338,  719,  306,  726,  710,  721,  710,  712,  722,  724,
      311,  713,  710,  708,  704,  707,  705,  699,    0,  702,
      337,  698,  697,  702,  691,    0,  332,  710,  326,  299,

      702,  693,  346,  691,  703,  690,  697,  696,  687,  698,
      813,  813,  813,  813,  813,  813,  694,  719,  375,  385,
        0,    0,    0,  813,    0,    0,  682,  813,  813,  386,
      387,    0,  722,  721,  813,  813,  813,  705,  705,  704,
      703,  674,    0,  691,  680,  689,  678,  683,  684,  669,
      667,  671,  335,  672,  681,    0,  679,  666,  674,  659,
      363,  666,  657,  670,  656,  672,  671,  666,  667,  667,
      654,  656,  655,  646,  659,  658,  643,  656,    0,  344,
      641,  648,  638,  637,  637,  646,  635,  639,  643,  646,
        0,  645,    0,    0,  645,  637,    0,  636,  631,    0,

        0,  246,  647,    0,  639,  666,  665,  664,  663,  662,
      653,  643,  644,  642,  617,  609,  627,  621,  629,    0,
      621,    0,  610,  622,  607,  616,  623,  603,  611,    0,
      612,  596,  614,  604,  611,  594,  607,    0,  601,  608,
      601,  592,  609,  590,  607,    0,  602,  586,  372,  588,
      585,    0,  585,  583,  600,  595,  590,  589,  580,  587,
      582,  591,  571,  573,    0,  572,    0,  585,  585,  813,
        0,  590,  813,  589,  813,  567,  590,  584,  594,  593,
      580,    0,  579,    0,  577,    0,    0,    0,    0,  565,
      560,  565,  570,  568,    0,  570,  555,    0,  562,  561,

      565,    0,  557,    0,  564,  557,  554,  552,  559,  549,
      560,  554,    0,  544,    0,  539,  554,  553,  538,  541,
      550,  545,  543,    0,    0,    0,    0,    0,    0,  552,
      813,  579,  553,  547,  546,  545,  541,  530,  531,  521,
      535,  520,    0,    0,  527,  532,  517,  524,  516,  509,
      524,  517,    0,  525,  524,  525,  523,  525,  524,  519,
      504,    0,  517,    0,    0,    0,    0,  813,  521,    0,
      520,  519,  499,    0,  512,  511,    0,    0,  514,  513,
      510,  507,    0,    0,    0,  498,  497,  509,  503,  493,
      503,  502,    0,  499,  503,  502,    0,    0,    0,    0,

        0,  484,  497,  491,    0,    0,  478,  477,  470,  477,
      468,  457,  447,  427,    0,  379,  375,    0,  364,  367,
      373,    0,    0,    0,    0,  365,    0,    0,    0,  373,
        0,  372,  369,  363,    0,    0,  813,  428,  438,  448,
      458,  468,  386,  343,   35,  472,   27,  474,  482,  490,
      493,  495,  499,  502,  504,  506,  512,  514,  516,  521,
      523,   24,   19,  525,  529,  531
    } ;

static yyconst short int yy_def[567] =
    {   0,
      538,  538,  539,  539,  540,  540,  541,  541,  542,  542,
      540,  540,  537,   13,  537,   15,  537,   17,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  543,  537,  544,  545,  537,  546,  537,
      537,  547,  537,  548,  537,  537,  537,  537,  537,  549,
      550,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  551,  537,  537,  537,  537,  537,  537,  537,
      552,  537,  537,  537,  537,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  537,  537,  537,  537,

      537,  537,  537,  537,  537,  537,  553,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  554,  555,  537,  546,
      556,  537,  548,  537,  549,  557,  558,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  549,  537,  537,  551,  559,  559,  537,
      537,  537,  537,  537,  537,  537,  537,  552,  537,  537,
      537,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,

      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      537,  537,  537,  537,  537,  537,  537,  537,  553,  560,
      554,  555,  556,  537,  561,  558,  537,  537,  537,  537,
      537,  559,  537,  559,  537,  537,  537,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  537,  562,

      563,  537,  564,  561,  537,  537,  537,  537,  537,  537,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  537,
      565,  566,  537,  564,  537,  537,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,

      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  565,  566,
      537,  537,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  537,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,

      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,    0,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537
    } ;

static yyconst short int yy_nxt[885] =
    {   0,
      537,  537,   21,   21,   24,   24,   28,   32,   32,   28,
       33,   33,   34,   34,   29,   25,   25,   29,  102,  130,
      133,  137,   22,   22,  128,  129,  372,  135,  138,  139,
      134,  371,  101,  131,  121,  103,  136,  151,  152,  153,
      154,  155,  118,   30,   35,   35,   30,   26,   26,   26,
       26,   26,   26,   26,   37,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   38,   26,   26,   26,
       26,   26,   26,   26,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   40,   26,   41,   26,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,

       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   42,   26,   26,   26,   26,
       26,   26,   26,   26,   43,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   26,   26,   26,   26,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   26,   26,   26,   26,   45,
       46,   47,   46,   48,   49,   50,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   72,   73,   74,
       75,   76,   77,   78,   79,   80,   81,   82,   83,   71,
       84,   71,   85,   71,   86,   87,   88,   71,   89,   90,
       91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
      105,  108,  126,  109,  146,  302,  147,  126,  156,  157,
      126,  126,  126,  126,  126,  126,  126,  140,  149,  141,
      143,  159,  163,  142,  167,  144,  373,  168,  187,  106,
      145,  188,  169,  164,  149,  110,  126,  165,  166,  170,

      189,  202,  171,  111,  112,  172,  190,  191,  212,  173,
      203,  113,  192,  174,  176,  114,  204,  115,  175,  116,
      160,  205,  177,  178,  179,  182,  194,  206,  197,  216,
      195,  198,  180,  183,  181,  184,  200,  218,  185,  201,
      207,  159,  285,  141,  186,  141,  146,  233,  147,  233,
      117,  254,  234,  213,  255,  230,  126,  231,  286,  220,
      149,  126,  263,  217,  126,  126,  126,  126,  126,  126,
      126,  230,  264,  231,  238,  239,  149,  240,  247,  241,
      160,  251,  273,  280,  283,  248,  249,  284,  281,  289,
      126,  218,  301,  107,  252,  325,  326,  274,  275,  354,

      306,  308,  306,  308,  302,  307,  309,  355,  290,  333,
      536,  334,  291,  220,  335,  410,  535,  534,  533,  411,
      532,  531,  530,  336,  529,  528,  527,  337,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,  120,  120,
      123,  123,  125,  526,  125,  125,  125,  125,  125,  125,
      125,  125,  127,  525,  127,  127,  127,  127,  148,  148,

      148,  158,  158,  219,  524,  219,  219,  219,  221,  221,
      222,  222,  223,  223,  225,  523,  225,  225,  225,  225,
      226,  226,  232,  232,  303,  522,  521,  303,  303,  304,
      304,  374,  374,  520,  374,  429,  429,  430,  430,  519,
      430,  518,  517,  516,  515,  514,  513,  512,  511,  510,
      509,  508,  507,  506,  505,  504,  503,  502,  501,  500,
      499,  498,  497,  496,  495,  494,  493,  492,  491,  490,
      489,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  478,  477,  476,  475,  474,  473,  472,  471,  470,
      469,  468,  431,  467,  466,  465,  464,  463,  462,  461,

      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  375,
      431,  428,  427,  426,  425,  424,  423,  422,  421,  420,
      419,  418,  417,  416,  415,  414,  413,  412,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  310,  309,  309,  307,  307,  376,  375,  370,  369,
      368,  367,  366,  365,  364,  363,  362,  361,  360,  359,

      358,  357,  356,  353,  352,  351,  350,  349,  348,  347,
      346,  345,  344,  343,  342,  341,  340,  339,  256,  338,
      332,  331,  330,  329,  328,  327,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  312,  311,
      234,  310,  305,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  288,  287,  282,  279,  278,  277,  276,  272,
      271,  270,  269,  268,  267,  266,  265,  262,  261,  260,
      259,  258,  257,  256,  253,  250,  246,  245,  244,  243,
      242,  237,  236,  235,  229,  228,  227,  224,  119,  215,
      214,  211,  210,  209,  208,  199,  196,  193,  162,  161,

      129,  150,  132,  124,  122,  119,  104,  101,  101,  537,
       36,   36,   19,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537
    } ;

static yyconst short int yy_chk[885] =
    {   0,
        0,    0,    1,    2,    3,    4,    7,    9,   10,    8,
        9,   10,    9,   10,    7,    3,    4,    8,   22,   53,
       57,   60,    1,    2,   52,   52,  563,   58,   60,   60,
       57,  562,   22,   53,  547,   22,   58,   66,   66,   66,
       67,   67,  545,    7,    9,   10,    8,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       30,   35,   51,   35,   63,  302,   63,   51,   68,   68,
       51,   51,   51,   51,   51,   51,   51,   61,   63,   61,
       62,   72,   77,   61,   78,   62,  302,   78,   83,   30,
       62,   83,   79,   77,   63,   35,   51,   77,   77,   79,

       84,   91,   79,   35,   35,   79,   84,   84,   98,   80,
       91,   35,   84,   80,   81,   35,   92,   35,   80,   35,
       72,   92,   81,   81,   81,   82,   86,   93,   88,  103,
       86,   88,   81,   82,   81,   82,   90,  107,   82,   90,
       93,  159,  200,  141,   82,  146,  147,  149,  147,  149,
      544,  173,  149,   98,  173,  141,  126,  146,  200,  107,
      147,  126,  181,  103,  126,  126,  126,  126,  126,  126,
      126,  141,  181,  146,  162,  162,  147,  162,  169,  162,
      159,  171,  191,  197,  199,  169,  169,  199,  197,  203,
      126,  219,  220,  543,  171,  253,  253,  191,  191,  280,

      230,  231,  230,  231,  220,  230,  231,  280,  203,  261,
      534,  261,  203,  219,  261,  349,  533,  532,  530,  349,
      526,  521,  520,  261,  519,  517,  516,  261,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  540,  540,
      540,  540,  540,  540,  540,  540,  540,  540,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  546,  546,
      548,  548,  549,  514,  549,  549,  549,  549,  549,  549,
      549,  549,  550,  513,  550,  550,  550,  550,  551,  551,

      551,  552,  552,  553,  512,  553,  553,  553,  554,  554,
      555,  555,  556,  556,  557,  511,  557,  557,  557,  557,
      558,  558,  559,  559,  560,  510,  509,  560,  560,  561,
      561,  564,  564,  508,  564,  565,  565,  566,  566,  507,
      566,  504,  503,  502,  496,  495,  494,  492,  491,  490,
      489,  488,  487,  486,  482,  481,  480,  479,  476,  475,
      473,  472,  471,  469,  463,  461,  460,  459,  458,  457,
      456,  455,  454,  452,  451,  450,  449,  448,  447,  446,
      445,  442,  441,  440,  439,  438,  437,  436,  435,  434,
      433,  432,  430,  423,  422,  421,  420,  419,  418,  417,

      416,  414,  412,  411,  410,  409,  408,  407,  406,  405,
      403,  401,  400,  399,  397,  396,  394,  393,  392,  391,
      390,  385,  383,  381,  380,  379,  378,  377,  376,  374,
      372,  369,  368,  366,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  351,  350,  348,  347,
      345,  344,  343,  342,  341,  340,  339,  337,  336,  335,
      334,  333,  332,  331,  329,  328,  327,  326,  325,  324,
      323,  321,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  303,  299,  298,
      296,  295,  292,  290,  289,  288,  287,  286,  285,  284,

      283,  282,  281,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      260,  259,  258,  257,  255,  254,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  242,  241,  240,  239,  238,
      234,  233,  227,  218,  217,  210,  209,  208,  207,  206,
      205,  204,  202,  201,  198,  195,  194,  193,  192,  190,
      188,  187,  186,  185,  184,  183,  182,  180,  179,  178,
      177,  176,  175,  174,  172,  170,  168,  167,  165,  164,
      163,  157,  154,  151,  140,  133,  132,  124,  119,  102,
      101,   97,   96,   95,   94,   89,   87,   85,   76,   75,

       69,   64,   55,   48,   43,   38,   25,   21,   20,   19,
       12,   11,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537,  537,  537,  537,  537,  537,  537,
      537,  537,  537,  537
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "E:\\Projects\\php_comp\\src\\lexer.l"
#define INITIAL 0
/* i hate compilers */
/* i hate visual studio */
/* if you fear/hate sharing your ideas, don't use my stupid tool */
/* i hate compilers */
/* i hate visual studio */
/* if you fear/hate sharing your ideas, don't use my stupid tool */
#line 12 "E:\\Projects\\php_comp\\src\\lexer.l"
  #include <unistd.h>
  #include <iostream>
  #include <string>
  #include <string.h>
  #include <queue>
  #include <stack>
  #include "grammar.hpp"
  #include "definitions.h"
  #include "Logger.hpp"
  #include "AST/Node.hpp"

  using namespace std;
  int line_no = 1;
  int col_no = 1;
  string inline_html;
  string str;
  queue<int> tokens_queue;
  Logger l("lexer_log.txt");
  extern ErrorRecovery errorRec;
  struct bracket {
    char br;
    int line_no;
    int col_no;
  };
  stack<bracket> brackets;

  void doForReturn(char *yytext){
    yylval.r.col_no = col_no;
    yylval.r.line_no = line_no;
    yylval.r.node = new Node();
    yylval.r.symbol = nullptr;
    yylval.r.scope = nullptr;
    col_no += strlen(yytext);
}

#define multi_line_comment 1

#define string 2

#define s_string 3
#define d_string 4

#define variable_substitution 5
#define variable_substitution_array 6
#define variable_substitution_property 7

#define php 8

#line 800 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 64 "E:\\Projects\\php_comp\\src\\lexer.l"



  /* this piece of code gonna be placed in the beginnig of yylex() */
  /* it handles returnig multiple tokens */
  while (!tokens_queue.empty()) {
    int token = tokens_queue.front();
    tokens_queue.pop();
    l.log("token", 0);
    l.log(token);
    return token;
  }


#line 966 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 538 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 813 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 79 "E:\\Projects\\php_comp\\src\\lexer.l"
case 2:
#line 80 "E:\\Projects\\php_comp\\src\\lexer.l"
case 3:
YY_RULE_SETUP
#line 80 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  BEGIN php;
  l.log("T_OPEN_TAG");
  yylval.r.token_type = NORMAL;
  doForReturn(yytext);
  return T_OPEN_TAG;
}
	YY_BREAK
case 4:
#line 89 "E:\\Projects\\php_comp\\src\\lexer.l"
case 5:
YY_RULE_SETUP
#line 89 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  BEGIN php;
  l.log("T_OPEN_TAG");
  yylval.r.token_type = WITH_ECHO;
  doForReturn(yytext);
  return T_OPEN_TAG;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 97 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  BEGIN INITIAL;
  if (!brackets.empty()) {
    char msg[128];
    bracket b = brackets.top();
    sprintf(msg, "Unexpected end of code: %c at line %d column %d should be matched", b.br, b.line_no, b.col_no);
    errorRec.errQ->enqueue(line_no, col_no, msg, "");
    errorRec.printErrQueue();
    yyterminate();
  }
  doForReturn(yytext);
  l.log("T_CLOSE_TAG");
  return T_CLOSE_TAG;
}
	YY_BREAK
case 7:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 112 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  if (yytext[0] == '\n') {
    ++line_no;
    col_no = 1;
  } else {
    ++col_no;
  }
  inline_html.push_back(yytext[0]);
  l.log("T_INLINE_HTML:");
  l.log(inline_html);
  yylval.r.str = new char[inline_html.size() + 1];
  strcpy(yylval.r.str, inline_html.c_str());
  inline_html.clear();
  return T_INLINE_HTML;
}
	YY_BREAK
case YY_STATE_EOF(php):
#line 128 "E:\\Projects\\php_comp\\src\\lexer.l"
{errorRec.errQ->enqueue(line_no, col_no, "unexpected end of file: missing ?>",""); errorRec.printErrQueue(); yyterminate();}
	YY_BREAK
case 8:
#line 131 "E:\\Projects\\php_comp\\src\\lexer.l"
case 9:
YY_RULE_SETUP
#line 131 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  if (yytext[0] == '\n') {
    ++line_no;
    col_no = 1;
  } else {
    ++col_no;
  }
  inline_html.push_back(yytext[0]);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 141 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  inline_html.push_back(yytext[0]);
  l.log("T_INLINE_HTML");
  l.log(inline_html);
  yylval.r.str = new char[inline_html.size() + 1];
  strcpy(yylval.r.str, inline_html.c_str());
  inline_html.clear();
  /* token 0 indicates the end of file */
  tokens_queue.push(0);
  return T_INLINE_HTML;
}
	YY_BREAK

case 10:
YY_RULE_SETUP
#line 154 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    l.log("SINGLE_LINE_COMMENT");
    doForReturn(yytext);
  }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 159 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    BEGIN multi_line_comment;
    col_no += 2;
    l.log("MULTI_LINE_COMMENT");
  }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 165 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    col_no = 1;
    line_no++;
  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 170 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    ++col_no;
  }
	YY_BREAK


case 14:
YY_RULE_SETUP
#line 176 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    BEGIN php;
    col_no += 2;
    l.log("END_MULTI_LINE_COMMENT");
  }
	YY_BREAK
case YY_STATE_EOF(multi_line_comment):
#line 182 "E:\\Projects\\php_comp\\src\\lexer.l"
{errorRec.errQ->enqueue(line_no, col_no, "unexpected end of file: unclosed multi-line comment",""); errorRec.printErrQueue(); yyterminate();}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 184 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    ++col_no;
  }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 188 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    ++line_no;
    col_no = 1;
  }
	YY_BREAK


case 17:
YY_RULE_SETUP
#line 195 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    doForReturn(yytext);
    yylval.r.i = atoi(yytext);
    l.log("T_INTEGER", 0); l.log(yylval.r.i);
    return T_LNUMBER;
  }
	YY_BREAK
case 18:
#line 203 "E:\\Projects\\php_comp\\src\\lexer.l"
case 19:
#line 204 "E:\\Projects\\php_comp\\src\\lexer.l"
case 20:
YY_RULE_SETUP
#line 204 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    doForReturn(yytext);
    yylval.r.f = atof(yytext);
    l.log("T_FLOAT", 0); l.log(yylval.r.f);
    return T_DNUMBER;
  }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 211 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    doForReturn(yytext);
    l.log("T_TRUE");
    return T_TRUE;
  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 217 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    doForReturn(yytext);
    l.log("T_FALSE");
    return T_FALSE;
  }
	YY_BREAK

case 23:
YY_RULE_SETUP
#line 223 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_ABSTRACT");
  return T_ABSTRACT;
}
	YY_BREAK
/* Strings */

case 24:
YY_RULE_SETUP
#line 231 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    BEGIN s_string;
    ++col_no;
  }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 236 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    BEGIN d_string;
    // double quoted strig might be splitted into multiple strings due to variables substitution
    // they should be grouped using ( )
    l.log("(");
    ++col_no;
    return '(';
  }
	YY_BREAK

/* single quoted string */
/* it accepts new lines (multiline string) */
/* it accepts only \\ and \' as escape characters, \n, \t, \r ... will be outputed literally */

case 26:
YY_RULE_SETUP
#line 250 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('\\'); ++col_no;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 252 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('\''); ++col_no;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 254 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('\n'); ++line_no; col_no = 1;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 256 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    yylval.r.str = new char[str.size() + 1];
    strcpy(yylval.r.str, str.c_str());
    l.log("single quoted string:"); l.log(str);
    str.clear();
    BEGIN php;
    return T_CONSTANT_ENCAPSED_STRING;
  }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 265 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back(yytext[0]); ++col_no;}
	YY_BREAK
case YY_STATE_EOF(s_string):
#line 267 "E:\\Projects\\php_comp\\src\\lexer.l"
{errorRec.errQ->enqueue(line_no, col_no, "unexpected end of file: unclosed string",""); errorRec.printErrQueue(); yyterminate();}
	YY_BREAK

/* double quoted string */
/* it has more more escape sequences for special characters than single quoted string */
/* it can handle variable substitution by spliting the string and variables into multiple concatenated strings and variables
  i.e: "i hate $smo because he's done $smth" --> ("i hate " . $smo . " because he's done " . $smth . "")
  note the parentheses, they are handled */

case 31:
YY_RULE_SETUP
#line 276 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('\n'); ++col_no;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 277 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('\r'); ++col_no;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 278 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('\t'); ++col_no;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 279 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('\e'); ++col_no;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 280 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('\v'); ++col_no;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 281 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('\f'); ++col_no;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 282 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('\\'); ++col_no;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 283 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('$'); ++col_no;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 284 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('"'); ++col_no;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 286 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back('\n'); ++line_no; col_no = 1;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 288 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    ++col_no;
    yylval.r.str = new char[str.size() + 1];
    strcpy(yylval.r.str, str.c_str());
    l.log("double quoted string:"); l.log(str);
    str.clear();
    tokens_queue.push(')');
    BEGIN php;
    return T_CONSTANT_ENCAPSED_STRING;
  }
	YY_BREAK
case 42:
#line 300 "E:\\Projects\\php_comp\\src\\lexer.l"
case 43:
#line 301 "E:\\Projects\\php_comp\\src\\lexer.l"
case 44:
YY_RULE_SETUP
#line 301 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    BEGIN variable_substitution_array;
    yylval.r.str = new char[str.size() + 1];
    strcpy(yylval.r.str, str.c_str());
    l.log("double quoted string: "); l.log(str);
    str.clear();
    tokens_queue.push('.');
    yyless(0);
    return T_CONSTANT_ENCAPSED_STRING;
  }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 312 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    BEGIN variable_substitution_property;
    yylval.r.str = new char[str.size() + 1];
    strcpy(yylval.r.str, str.c_str());
    l.log("double quoted string: "); l.log(str);
    str.clear();
    tokens_queue.push('.');
    yyless(0);
    return T_CONSTANT_ENCAPSED_STRING;
  }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 323 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    BEGIN variable_substitution;
    yylval.r.str = new char[str.size() + 1];
    strcpy(yylval.r.str, str.c_str());
    l.log("double quoted string: "); l.log(str);
    str.clear();
    tokens_queue.push('.');
    yyless(0);
    return T_CONSTANT_ENCAPSED_STRING;
  }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 334 "E:\\Projects\\php_comp\\src\\lexer.l"
{str.push_back(yytext[0]); ++col_no;}
	YY_BREAK
case YY_STATE_EOF(d_string):
#line 336 "E:\\Projects\\php_comp\\src\\lexer.l"
{errorRec.errQ->enqueue(line_no, col_no, "unexpected end of file: unclosed string",""); errorRec.printErrQueue(); yyterminate();}
	YY_BREAK


case 48:
YY_RULE_SETUP
#line 340 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    yylval.r.str = new char[yyleng + 1];
    strcpy(yylval.r.str, yytext);
    doForReturn(yytext);
    l.log("T_VARIABLE", 0); l.log(yytext);
    tokens_queue.push('.');
    BEGIN d_string;
    return T_VARIABLE;
  }
	YY_BREAK


case 49:
YY_RULE_SETUP
#line 352 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    yylval.r.str = new char[yyleng + 1];
    strcpy(yylval.r.str, yytext);
    doForReturn(yytext);
    l.log("T_VARIABLE", 0); l.log(yytext);
    return T_VARIABLE;
  }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 360 "E:\\Projects\\php_comp\\src\\lexer.l"
{
   doForReturn(yytext);
   l.log("[");
   return '[';
  }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 366 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    yylval.r.str = new char[yyleng + 1];
    strcpy(yylval.r.str, yytext);
    doForReturn(yytext);
    l.log("T_STRING", 0); l.log(yytext);
    return T_STRING;
  }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 374 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    yylval.r.i = atoi(yytext);
    doForReturn(yytext);
    l.log("T_INTEGER", 0); l.log(yylval.r.i);
    return T_LNUMBER;
  }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 381 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    doForReturn(yytext);
    l.log("]");
    BEGIN d_string;
    tokens_queue.push('.');
    return ']';
  }
	YY_BREAK


case 54:
YY_RULE_SETUP
#line 391 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    yylval.r.str = new char[yyleng + 1];
    strcpy(yylval.r.str, yytext);
    doForReturn(yytext);
    l.log("T_VARIABLE", 0); l.log(yytext);
    return T_VARIABLE;
  }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 399 "E:\\Projects\\php_comp\\src\\lexer.l"
{
   doForReturn(yytext);
   l.log("->");
   return T_OBJECT_OPERATOR;
  }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 405 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    yylval.r.str = new char[yyleng + 1];
    strcpy(yylval.r.str, yytext);
    doForReturn(yytext);
    l.log("T_STRING", 0); l.log(yylval.r.str);
    tokens_queue.push('.');
    BEGIN d_string;
    return T_STRING;
  }
	YY_BREAK


case 57:
#line 418 "E:\\Projects\\php_comp\\src\\lexer.l"
case 58:
#line 419 "E:\\Projects\\php_comp\\src\\lexer.l"
case 59:
#line 420 "E:\\Projects\\php_comp\\src\\lexer.l"
case 60:
#line 421 "E:\\Projects\\php_comp\\src\\lexer.l"
case 61:
#line 422 "E:\\Projects\\php_comp\\src\\lexer.l"
case 62:
#line 423 "E:\\Projects\\php_comp\\src\\lexer.l"
case 63:
#line 424 "E:\\Projects\\php_comp\\src\\lexer.l"
case 64:
#line 425 "E:\\Projects\\php_comp\\src\\lexer.l"
case 65:
#line 426 "E:\\Projects\\php_comp\\src\\lexer.l"
case 66:
#line 427 "E:\\Projects\\php_comp\\src\\lexer.l"
case 67:
#line 428 "E:\\Projects\\php_comp\\src\\lexer.l"
case 68:
#line 429 "E:\\Projects\\php_comp\\src\\lexer.l"
case 69:
#line 430 "E:\\Projects\\php_comp\\src\\lexer.l"
case 70:
#line 431 "E:\\Projects\\php_comp\\src\\lexer.l"
case 71:
#line 432 "E:\\Projects\\php_comp\\src\\lexer.l"
case 72:
#line 433 "E:\\Projects\\php_comp\\src\\lexer.l"
case 73:
#line 434 "E:\\Projects\\php_comp\\src\\lexer.l"
case 74:
#line 435 "E:\\Projects\\php_comp\\src\\lexer.l"
case 75:
#line 436 "E:\\Projects\\php_comp\\src\\lexer.l"
case 76:
#line 437 "E:\\Projects\\php_comp\\src\\lexer.l"
case 77:
YY_RULE_SETUP
#line 437 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    doForReturn(yytext);
    l.log(yytext);
    return yytext[0];
  }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 443 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    bracket b = {'[', line_no, col_no};
    brackets.push(b);
    doForReturn(yytext);
    l.log(yytext);
    return yytext[0];
  }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 451 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    doForReturn(yytext);
    if (!brackets.empty()) {
      bracket b = brackets.top();
      brackets.pop();
      if (b.br != '[') {
        char msg[128];
        sprintf(msg, "Unexpected ]: bracket %c at line %d column %d should be matched", b.br, b.line_no, b.col_no);
        errorRec.errQ->enqueue(line_no, col_no, msg, "");
        errorRec.printErrQueue();
        yyterminate();
      }
    } else {
      errorRec.errQ->enqueue(line_no, col_no, "stray ]", "");
      errorRec.printErrQueue();
      yyterminate();
    }
    l.log(yytext);
    return yytext[0];
  }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 472 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    bracket b = {'{', line_no, col_no};
    brackets.push(b);
    doForReturn(yytext);
    l.log(yytext);
    return yytext[0];
  }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 480 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    doForReturn(yytext);
    if (!brackets.empty()) {
      bracket b = brackets.top();
      brackets.pop();
      if (b.br != '{') {
        char msg[128];
        sprintf(msg, "Unexpected }: bracket %c at line %d column %d should be matched", b.br, b.line_no, b.col_no);
        errorRec.errQ->enqueue(line_no, col_no, msg, "");
        errorRec.printErrQueue();
        yyterminate();
      }
    } else {
      errorRec.errQ->enqueue(line_no, col_no, "stray }", "");
      errorRec.printErrQueue();
      yyterminate();
    }
    return yytext[0];
  }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 500 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    bracket b = {'(', line_no, col_no};
    brackets.push(b);
    doForReturn(yytext);
    l.log(yytext);
    return yytext[0];
  }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 508 "E:\\Projects\\php_comp\\src\\lexer.l"
{
    doForReturn(yytext);
    if (!brackets.empty()) {
      bracket b = brackets.top();
      brackets.pop();
      if (b.br != '(') {
        char msg[128];
        sprintf(msg, "Unexpected ): bracket %c at line %d column %d should be matched", b.br, b.line_no, b.col_no);
        errorRec.errQ->enqueue(line_no, col_no, msg, "");
        errorRec.printErrQueue();
        yyterminate();
      }
    } else {
      errorRec.errQ->enqueue(line_no, col_no, "stray )", "");
      errorRec.printErrQueue();
      yyterminate();
    }
    l.log(yytext);
    return yytext[0];
  }
	YY_BREAK

case 84:
YY_RULE_SETUP
#line 530 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_AND_EQUAL", 0); l.log(yytext);
  return T_AND_EQUAL;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 536 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_ARRAY");
  return T_ARRAY;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 542 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_SQUARE_BRACKETS");
  return T_SQUARE_BRACKETS;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 548 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_AS");
  return T_AS;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 554 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_BOOLEAN_AND");
  return T_BOOLEAN_AND;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 560 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_BOOLEAN_OR");
  return T_BOOLEAN_OR;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 566 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_BREAK");
  return T_BREAK;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 572 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_CALLBACK");
  return T_CALLBACK;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 578 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_CASE");
  return T_CASE;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 584 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_CATCH");
  return T_CATCH;
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 590 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_CLASS");
  return T_CLASS;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 596 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_CLASS_C");
  return T_CLASS_C;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 602 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_CLONE");
  return T_CLONE;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 608 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_CONCAT_EQUAL");
  return T_CONCAT_EQUAL;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 614 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_CONST");
  return T_CONST;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 620 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_CONTINUE");
  return T_CONTINUE;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 626 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_CURLY_OPEN");
  return T_CURLY_OPEN;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 632 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_DEC");
  return T_DEC;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 638 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_DECLARE");
  return T_DECLARE;
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 644 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_DEFAULT");
  return T_DEFAULT;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 650 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_DIR");
  return T_DIR;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 656 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_DIV_EQUAL");
  return T_DIV_EQUAL;
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 662 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_DO");
  return T_DO;
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 668 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_DOUBLE_ARROW");
  return T_DOUBLE_ARROW;
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 674 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("::");
  return T_PAAMAYIM_NEKUDOTAYIM;
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 680 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_ECHO");
  return T_ECHO;
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 686 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("...");
  return T_ELLIPSIS;
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 692 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_ELSE");
  return T_ELSE;
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 698 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_ELSEIF");
  return T_ELSEIF;
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 704 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_EMPTY");
  return T_EMPTY;
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 710 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_ENDDECLARE");
  return T_ENDDECLARE;
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 716 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_ENDFOR");
  return T_ENDFOR;
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 722 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  return T_ENDFOREACH;
  l.log("T_ENDFOREACH");
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 728 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_ENDIF");
  return T_ENDIF;
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 734 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_ENDSWITCH");
  return T_ENDSWITCH;
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 740 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_ENDWHILE");
  return T_ENDWHILE;
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 746 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_EVAL");
  return T_EVAL;
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 752 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_EXIT");
  return T_EXIT;
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 758 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_EXTENDS");
  return T_EXTENDS;
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 764 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_FILE");
  return T_FILE;
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 770 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_FINAL");
  return T_FINAL;
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 776 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_FINALLY");
  return T_FINALLY;
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 782 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_FOR");
  return T_FOR;
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 788 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_FOREACH");
  return T_FOREACH;
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 794 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_FUNCTION");
  return T_FUNCTION;
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 800 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_GLOBAL");
  return T_GLOBAL;
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 806 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_GOTO");
  return T_GOTO;
}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 812 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_IF");
  return T_IF;
}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 818 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_IMPLEMENTS");
  return T_IMPLEMENTS;
}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 824 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_INC");
  return T_INC;
}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 830 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_INCLUDE");
  return T_INCLUDE;
}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 836 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_INCLUDE_ONCE");
  return T_INCLUDE_ONCE;
}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 842 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_INSTANCEOF");
  return T_INSTANCEOF;
}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 848 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_INSTEADOF");
  return T_INSTEADOF;
}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 854 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_INTERFACE");
  return T_INTERFACE;
}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 860 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_ISSET");
  return T_ISSET;
}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 866 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_IS_EQUAL");
  return T_IS_EQUAL;
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 872 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_IS_GREATER_OR_EQUAL");
  return T_IS_GREATER_OR_EQUAL;
}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 878 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_IS_IDENTICAL");
  return T_IS_IDENTICAL;
}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 884 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_IS_NOT_EQUAL");
  return T_IS_NOT_EQUAL;
}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 890 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_IS_NOT_IDENTICAL");
  return T_IS_NOT_IDENTICAL;
}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 896 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_IS_SMALLER_OR_EQUAL");
  return T_IS_SMALLER_OR_EQUAL;
}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 902 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_LINE");
  return T_LINE;
}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 908 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_LIST");
  return T_LIST;
}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 914 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_LOGICAL_AND");
  return T_LOGICAL_AND;
}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 920 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_LOGICAL_OR");
  return T_LOGICAL_OR;
}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 926 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_LOGICAL_XOR");
  return T_LOGICAL_XOR;
}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 932 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_MINUS_EQUAL");
  return T_MINUS_EQUAL;
}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 938 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_MOD_EQUAL");
  return T_MOD_EQUAL;
}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 944 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_MUL_EQUAL");
  return T_MUL_EQUAL;
}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 950 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_NAMESPACE");
  return T_NAMESPACE;
}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 956 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_NEW");
  return T_NEW;
}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 962 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log(yytext);
  return T_OBJECT_OPERATOR;
}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 968 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_OR_EQUAL");
  return T_OR_EQUAL;
}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 974 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PLUS_EQUAL");
  return T_PLUS_EQUAL;
}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 980 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_POW");
  return T_POW;
}
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 986 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_POW_EQUAL");
  return T_POW_EQUAL;
}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 992 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PRINT");
  return T_PRINT;
}
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 998 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PRIVATE");
  return T_PRIVATE;
}
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 1004 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PUBLIC");
  return T_PUBLIC;
}
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 1010 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PROTECTED");
  return T_PROTECTED;
}
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 1016 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_REQUIRE");
  return T_REQUIRE;
}
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 1022 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_REQUIRE_ONCE");
  return T_REQUIRE_ONCE;
}
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 1028 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_RETURN");
  return T_RETURN;
}
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 1034 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_SL", 0); l.log(yytext);
  return T_SL;
}
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 1040 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_SL_EQUAL", 0); l.log(yytext);
  return T_SL_EQUAL;
}
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 1046 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_SR", 0); l.log(yytext);
  return T_SR;
}
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 1052 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_SR_EQUAL", 0); l.log(yytext);
  return T_SR_EQUAL;
}
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 1058 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_STATIC");
  return T_STATIC;
}
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 1064 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_SWITCH");
  return T_SWITCH;
}
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 1070 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_THROW");
  return T_THROW;
}
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 1076 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_TRAIT");
  return T_TRAIT;
}
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 1082 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_TRY");
  return T_TRY;
}
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 1088 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_UNSET");
  return T_UNSET;
}
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 1094 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  return T_UNSET_CAST;
}
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 1099 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_USE");
  return T_USE;
}
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 1105 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_VAR");
  return T_VAR;
}
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 1111 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_WHILE");
  return T_WHILE;
}
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 1117 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_XOR_EQUAL");
  return T_XOR_EQUAL;
}
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 1123 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_YIELD");
  return T_YIELD;
}
	YY_BREAK
/* Types */
case 184:
YY_RULE_SETUP
#line 1130 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PRIMITIVE: T_INT");
  yylval.r.token_type = T_PRIMITIVE_INTEGER;
  return T_PRIMITIVE;
}
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 1137 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PRIMITIVE: T_DOUBLE");
  yylval.r.token_type = T_PRIMITIVE_DOUBLE;
  return T_PRIMITIVE;
}
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 1144 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PRIMITIVE: T_FLOAT");
  yylval.r.token_type = T_PRIMITIVE_FLOAT;
  return T_PRIMITIVE;
}
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 1151 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PRIMITIVE: T_CHAR");
  yylval.r.token_type = T_PRIMITIVE_CHAR;
  return T_PRIMITIVE;
}
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 1158 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PRIMITIVE: BOOLEAN");
  yylval.r.token_type = T_PRIMITIVE_BOOLEAN;
  return T_PRIMITIVE;
}
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 1165 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PRIMITIVE: STRING");
  yylval.r.token_type = T_PRIMITIVE_STRING;
  return T_PRIMITIVE;
}
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 1172 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  l.log("T_PRIMITIVE: VOID");
  yylval.r.token_type = T_PRIMITIVE_VOID;
  return T_PRIMITIVE;
}
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 1179 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  yylval.r.str = new char[yyleng + 1];
  strcpy(yylval.r.str, yytext);
  l.log("T_STRING", 0); l.log(yytext);
  return T_STRING;
}
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 1187 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  yylval.r.str = new char[yyleng + 1];
  strcpy(yylval.r.str, yytext);
  l.log("T_VARIABLE", 0); l.log(yytext);
  return T_VARIABLE;
}
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 1195 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  yylval.r.str = new char[yyleng + 1];
  strcpy(yylval.r.str, yytext);
  char msg[128];
  sprintf(msg, "Bad name '%s': names can't start with a digit", yytext);
  errorRec.errQ->enqueue(line_no, col_no, msg, "");
  l.log("T_STRING: BAD", 0); l.log(yytext);
  return T_STRING;
}
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 1206 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  yylval.r.str = new char[yyleng + 1];
  strcpy(yylval.r.str, yytext);
  char msg[128];
  sprintf(msg, "Bad variable name '%s': variables names can't start with a digit or a punctuation", yytext);
  errorRec.errQ->enqueue(line_no, col_no, msg, "");
  l.log("T_VARIABLE: BAD", 0); l.log(yytext);
  return T_VARIABLE;
}
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 1216 "E:\\Projects\\php_comp\\src\\lexer.l"
{
  doForReturn(yytext);
  char msg[128];
  sprintf(msg, "Unexpected character '%c'", yytext);
  errorRec.errQ->enqueue(line_no, col_no, msg, "");
  l.log("T_BAD_INPUT", 0); l.log(yytext);
  return T_BAD_INPUT;
}
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 1225 "E:\\Projects\\php_comp\\src\\lexer.l"
ECHO;
	YY_BREAK
#line 2753 "lex.yy.c"
case YY_STATE_EOF(string):
case YY_STATE_EOF(variable_substitution):
case YY_STATE_EOF(variable_substitution_array):
case YY_STATE_EOF(variable_substitution_property):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 538 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 538 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 537);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 1225 "E:\\Projects\\php_comp\\src\\lexer.l"

